// Generated by https://quicktype.io

class DistributionData {
  int id;
  String name;
  String slug;
  String tdwgCode;
  int tdwgLevel;
  int speciesCount;
  DistributionDataLinks links;

  DistributionData({
    this.id,
    this.name,
    this.slug,
    this.tdwgCode,
    this.tdwgLevel,
    this.speciesCount,
    this.links,
    });
  DistributionData.fromJsonMap(Map<String, dynamic> json) {
    id = json["id"];
    name=json["name"];
    slug=json["slug"];
    tdwgCode=json["tdwg_code"];
    tdwgLevel=json["tdwg_level"];
    speciesCount=json["species_count"];
    links=DistributionDataLinks.fromJsonMap(json["links"]);
  }
}

class DistributionDataLinks {
  String self;
  String plants;
  String species;

  DistributionDataLinks({
    this.self,
    this.plants,
    this.species,
  });
  DistributionDataLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    plants = json['plants'];
    species = json['species'];
  }
}
