// Generated by https://quicktype.io

import 'package:myapp/models/subkingdom.dart';

class ListDivision {
  List<Division> items = [];
  ListDivisionLinks links;
  MetaData meta;

  ListDivision.fromJsonList(dynamic jsonList) {
    if (jsonList == null) return;

    links = ListDivisionLinks.fromJsonMap(jsonList['links']);
    meta = MetaData.fromJsonMap(jsonList['meta']);
    for (var item in jsonList['data']) {
      final data = new Division.fromJsonMap(item);
      items.add(data);
    }
  }
}
class MetaData {
  int total;

  MetaData(this.total);
  MetaData.fromJsonMap(Map<String, dynamic> json) {
    total = json['total'];
  }
}

class Division {
  int id;
  String name;
  String slug;
  DivisionLinks links;
  SubKingdom subkingdom;

  Division({
    this.id,
    this.name,
    this.slug,
    this.links,
    this.subkingdom,
  });
  Division.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    slug = json['slug'];
    links = DivisionLinks.fromJsonMap(json['links']);
    subkingdom =  SubKingdom.fromJsonMap(json['subkingdom']);
  }
}

class DivisionLinks {
  String self;
  String subkingdom;

  DivisionLinks({
    this.self,
    this.subkingdom,
  });
  DivisionLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    subkingdom = json['subkingdom'];
  }
}

class ListDivisionLinks {
  String self;
  String first;
  String last;
  String next;
  String prev;

  ListDivisionLinks({this.self, this.first, this.last});
  ListDivisionLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    first = json['first'];
    last = json['last'];
    next = json['next'];
    prev = json['prev'];
  }
}

