// Generated by https://quicktype.io

import 'package:myapp/models/division.dart';
class ListDivisionClass {
  List<DivisionClass> items = new List();

  ListDivisionClass();

  ListDivisionClass.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final elem = new DivisionClass.fromJsonMap(item);
      items.add(elem);
    }
  }
}

class DivisionClass {
  int id;
  String name;
  String slug;
  DivisionClassLinks links;
  Division division;

  DivisionClass({
    this.id,
    this.name,
    this.slug,
    this.links,
    this.division,
  });
  DivisionClass.fromJsonMap(Map<String, dynamic> json) {
    id = json['id']!=null?json['id']:null;
    name = json['name']!=null?json['name']:null;
    slug = json['slug']!=null?json['slug']:null;
    links = json['links']!=null?DivisionClassLinks.fromJsonMap(json['links']):null;
    division = json['division']!=null?Division.fromJsonMap(json['division']):null;
  }
}

class DivisionClassLinks {
  String self;
  String division;

  DivisionClassLinks({
    this.self,
    this.division,
  });
  DivisionClassLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    division = json['division'];

  }
}
