// Generated by https://quicktype.io

import 'package:myapp/models/division_class.dart';

class ListDivisionOrder {
  List<DivisionOrder> items = [];
  ListDivisionOrderLinks links;
  MetaData meta;

  ListDivisionOrder.fromJsonList(dynamic jsonList) {
    //print(jsonList);
    if (jsonList == null) return;

    links = ListDivisionOrderLinks.fromJsonMap(jsonList['links']);
    meta = MetaData.fromJsonMap(jsonList['meta']);
    for (var item in jsonList['data']) {
      final data = new DivisionOrder.fromJsonMap(item);
      items.add(data);
    }
  }
}

class MetaData {
  int total;

  MetaData(this.total);
  MetaData.fromJsonMap(Map<String, dynamic> json) {
    total = json['total'];
  }
}


class DivisionOrder {
  int id;
  String name;
  String slug;
  DivisionOrderLinks links;
  DivisionClass divisionClass;

  DivisionOrder({
    this.id,
    this.name,
    this.slug,
    this.links,
    this.divisionClass,
  });
  DivisionOrder.fromJsonMap(Map<String, dynamic> json) {
    id = json['id']!=null?json['id']:null;
    name = json['name']!=null?json['name']:null;
    slug = json['slug']!=null?json['slug']:null;
    links = json['links']!=null?DivisionOrderLinks.fromJsonMap(json['links']):null;
    divisionClass = json['division_class']!=null?DivisionClass.fromJsonMap(json['division_class']):null;
  }
}

class DivisionOrderLinks {
  String self;
  String divisionClass;

  DivisionOrderLinks({
    this.self,
    this.divisionClass,
  });
  DivisionOrderLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    divisionClass = json['division_order'];

  }
}
class ListDivisionOrderLinks {
  String self;
  String first;
  String last;
  String next;
  String prev;

  ListDivisionOrderLinks({this.self, this.first, this.last});
  ListDivisionOrderLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    first = json['first'];
    last = json['last'];
    next = json['next'];
    prev = json['prev'];
  }
}

