// Generated by https://quicktype.io

import 'package:myapp/models/division_order.dart';

class Family {
  int id;
  String name;
  String commonName;
  String slug;
  FamilyLinks links;
  DivisionOrder divisionOrder;

  Family({
    this.id,
    this.name,
    this.commonName,
    this.slug,
    this.links,
    this.divisionOrder,
  });
  Family.fromJsonMap(Map<String, dynamic> json) {
    id = json['id']!=null?json['id']:null;
    name = json['name']!=null?json['name']:null;
    commonName = json['commonName']!=null?json['commonName']:null;
    slug = json['slug']!=null?json['slug']:null;
    links = json['links']!=null?FamilyLinks.fromJsonMap(json['links']):null;
    divisionOrder = json['divisionOrder']!=null?DivisionOrder.fromJsonMap(json['division_order']):null;
  }
}

class FamilyLinks {
  String self;
  String divisionOrder;
  String genus;

  FamilyLinks({
    this.self,
    this.divisionOrder,
    this.genus,
  });
  FamilyLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    divisionOrder = json['division_order'];
    genus = json['genus'];
  }
}
