// Generated by https://quicktype.io

import 'package:myapp/models/kingdom.dart';

class ListSubKingdom {
  List<SubKingdom> items = new List();

  ListSubKingdom();

  ListSubKingdom.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final subkingdom = new SubKingdom.fromJsonMap(item);
      items.add(subkingdom);
    }
  }
}

class SubKingdom {
  int id;
  String name;
  String slug;
  SubKingdomLinks links;
  Kingdom kingdom;

  SubKingdom({
    this.id,
    this.name,
    this.slug,
    this.links,
    this.kingdom,
  });

  SubKingdom.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    slug = json['slug'];
    links = SubKingdomLinks.fromJsonMap(json['links']);
    kingdom =  Kingdom.fromJsonMap(json['kingdom']);
  }
}

class SubKingdomLinks {
  String self;
  String kingdom;

  SubKingdomLinks({
    this.self,
    this.kingdom,
  });

  SubKingdomLinks.fromJsonMap(Map<String, dynamic> json) {
    self = json['self'];
    kingdom = json['kingdom'];
  }
}
